apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend-deployment
spec:
  selector:
    matchLabels:
      app: spring-backend-deployment
  template:
    metadata:
      labels:
        app: spring-backend-deployment
    spec:
      containers:
      - name: spring-backend-deployment
        image: architdev/spring-backend:0.3
        ports:
        - containerPort: 8080
        env:
          - name:  SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name:  postgres-configmap
                key: url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                 name:  postgres-secret
                 key:  username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name:  postgres-secret
                 key:  password
